### ISSUE TITLE
[1.12] Crashing when booting up a server

### ISSUE THREAD

**Issue by Gbergz** [Hennamann/Mist-Core#6]
As the title says the server crashes when loading up.
Crashlog here: [Pastebin](https://pastebin.com/7SZxKk43)

**Comment by Hennamann** [comment]
Oh, whoopsie. Looks like it tries to run client-side events on the server. I probably forgot to limit the event to the client. I will have it fixed soon. Thank you for reporting this!

**Comment by Hennamann** [comment]
Fixed. will push the update to curse later, here's a maven download in the meantime: https://maven.henrikstabell.com/com/henrikstabell/mistcore/MistCore-1.12/1.2.0-0/MistCore-1.12-1.2.0-0-universal.jar
