### ISSUE TITLE
[1.12.2] Crash When loading server: NoSuchMethodError

### ISSUE THREAD

**Issue by Morpheus1101** [Hennamann/Mist-Core#7]
Crash log @ https://gist.github.com/Morpheus1101/9f96ab7b1a76f34ac7d1a09af7997ca4

**Comment by Hennamann** [comment]
This is the same crash as #6 but it seems like it's the latest version with the fix. I might have derped when adding the fix. I'll fix it right away.

Note not sure why, but it seems like the Gases mod has errored too. Might be because of this crash though.

**Comment by Hennamann** [comment]
This should now be fixed with version 1.2.1 which should be on Curse soon. Until then you can download it here: https://maven.henrikstabell.com/com/henrikstabell/mistcore/MistCore-1.12/1.2.1-1/MistCore-1.12-1.2.1-1-universal.jar

**Comment by Morpheus1101** [comment]
Thanks for the quick fix and yes gasses was also crashing which i got solved as well :D
